# Generated by Django 5.2.4 on 2025-07-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_tab_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='extraction_method',
            field=models.CharField(default='OCR', max_length=50),
        ),
    ]
