# Generated by Django 5.2.4 on 2025-07-31 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_extraction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.tab'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='notes.tab')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('tab', 'name')},
            },
        ),
        migrations.AddField(
            model_name='note',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.unit'),
        ),
    ]
